### ISSUE TITLE
Error on block from stable_diffusion_videos import interface  interface.launch(debug=True)

### ISSUE THREAD

**Issue by DisDoh** [PsorTheDoctor/Sekcja-SI#1]
---------------------------------------------------------------------------

HTTPError                                 Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    212     try:
--> 213         response.raise_for_status()
    214     except HTTPError as e:

12 frames

HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/CompVis/stable-diffusion-v1-4/resolve/fp16/model_index.json

The above exception was the direct cause of the following exception:

HfHubHTTPError                            Traceback (most recent call last)

HfHubHTTPError: <class 'requests.exceptions.HTTPError'> (Request ID: 7diCQ859jx0yQQmvX6Cu9)

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py](https://localhost:8080/#) in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    254             except HTTPError as err:
    255                 raise EnvironmentError(
--> 256                     "There was a specific connection error when trying to load"
    257                     f" {pretrained_model_name_or_path}:\n{err}"
    258                 )

OSError: There was a specific connection error when trying to load CompVis/stable-diffusion-v1-4:
<class 'requests.exceptions.HTTPError'> (Request ID: 7diCQ859jx0yQQmvX6Cu9)

**Comment by PsorTheDoctor** [comment]
I just tested and it works for me. Did you switch to GPU and logged into the Hugging Face?

**Comment by DisDoh** [comment]
I had to accept a policy from stable diffusion on hugging
